apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    kubernetes.io/ingress.class: nginx      
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.ingress.host1 }}
      http:
        paths:
        - path: {{ .Values.ingress.path1 }}
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.service.name }}
              port:
                number: {{ .Values.service.port }}

    - host: {{ .Values.ingress.host2 }}
      http:
        paths:
          - path: {{ .Values.ingress.path2 }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.port }}

