apiVersion: v1
kind: Service
metadata:
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
  labels:
{{ toYaml .Values.labels | indent 4 }}
  name: {{ .Values.service.name }}
spec:
  ports:
    - name: https
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.containerPort }}
  selector:
  {{ toYaml .Values.labels | indent 4 }}
  sessionAffinity: None
  type: {{ .Values.service.type }}