apiVersion: "v1"
kind: "Pod"
metadata:
  annotations: {}
  labels:
    jenkins: "slave"
    jenkins/jenkins-apsw: "true"
spec:
  containers:
    - args:
        - "cat"
      command:
        - "/bin/sh"
        - "-c"
      image: "sam0392in/sam:jenkins-python-builder"
      imagePullPolicy: "IfNotPresent"
      name: "python-aws"
      env:
      - name: "DOCKER_CONFIG"
        value: "/home/jenkins/.docker/"
      resources:
        limits: {}
        requests:
          memory: "100Mi"
      securityContext:
        privileged: true
      tty: true
      volumeMounts:
        - mountPath: "/var/run/docker.sock"
          name: "volume-0"
          readOnly: false
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
          readOnly: false
#        - mountPath: "/home/jenkins/.aws"
#          name: "volume-1"
#          readOnly: false
        - mountPath: "/home/jenkins/.docker"
          name: "volume-2"

      workingDir: "/home/jenkins/agent"

  nodeSelector: {}
  restartPolicy: "Never"
  serviceAccount: "jenkins"
  volumes:
    - name: "volume-0"
      hostPath:
        path: "/var/run/docker.sock"
#    - name: "volume-1"
#      secret:
#        secretName: "aws"
    - name: "volume-2"
      secret:
        secretName: "docker-cfg"      
    - emptyDir:
        medium: ""
      name: "workspace-volume"
